
CREATE DATABASE IF NOT EXISTS subject_rating_dev DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;

USE subject_rating_dev
-- 用户表
CREATE TABLE IF NOT EXISTS users (
    `id` INT AUTO_INCREMENT,
    user_name VARCHAR(40) NOT NULL UNIQUE,
    wid VARCHAR(32) NULL UNIQUE,
    phone VARCHAR(20) NULL UNIQUE,
    email VARCHAR(100) NULL UNIQUE,
    hashed_password VARCHAR(100) NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    is_locked TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
)ENGINE=InnoDB;